Change giver fields
capgemini-stavanger/gi-en-jul pull request #141
Opened 2021-07-01 07:22 UTC by elisabethnetland

Closes #124 
Possibility to change giver fields in SummaryRegistration
Changed bottom buttons to material UI design.

2021-07-01 08:47 UTC, TheseusDeus approved these changes

2021-07-01 08:53 UTC, joffe97 requested changes
I see that there is some conflicts with task #139. I can continue on this issue, and fix the merge conflicts and change the TextValidators into InputValidators if you want.

2021-07-01 08:53 UTC, joffe97 commented on GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
> +            errors.setErrorPhoneText('Telefonnummeret ditt ser litt rart ut, er den skrevet riktig?')
These error text changes will most likely conflict with #139.

2021-07-01 08:53 UTC, joffe97 commented on GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
> +                        <TextValidator
The InputValidator from #139 should be used instead of the TextValidator class. This way we handle all validation from one single component.

2021-07-01 12:27 UTC, Sommerli submitted a review, later dismissed

2021-07-02 10:05 UTC, joffe97 approved these changes

2021-07-02 10:05 UTC, merged