Added generation of delivery excel. Added familyid to connection
capgemini-stavanger/gi-en-jul pull request #288
Opened 2021-07-26 09:15 UTC by joffe97

2021-07-26 10:40 UTC, TheseusDeus requested changes
No description on either the issues or the PR about how it works, 
this should be present
Some other minor formatting suggestions

2021-07-26 10:40 UTC, TheseusDeus commented on GiEnJul/Controllers/AdminController.cs
> +using System.Net.Http;
Is this line necessary? work fine without line 16

2021-07-26 10:40 UTC, TheseusDeus commented on GiEnJul/Entities/Connection.cs
> +
remove newline

2021-07-27 08:12 UTC, Sommerli commented on GiEnJul/Entities/Connection.cs
> +            SubmitterPhoneNumber = recipient.ContactPhoneNumber;
Nice catch 👍

2021-07-27 08:48 UTC, RonHaland reviewed
Not sure how much value Task.Run() gives us here. I would just remove it and make the method synchronous.

2021-07-27 08:48 UTC, RonHaland commented on GiEnJul/Utilities/ExcelGenerator.cs
> +            {
This probably shouldn't be in a Task.Run

2021-07-27 12:46 UTC, TheseusDeus submitted a review, later dismissed

2021-07-27 13:15 UTC, RonHaland commented on GiEnJul/Utilities/ExcelGenerator.cs
> +                foreach (var header in entry.AsOrderedDictionary().Keys)
```suggestion
            var headers = excelEntries?.FirstOrDefault().AsOrderedDictionary().Keys ?? new List<string>();
            foreach (var header in headers)
```

2021-07-27 14:26 UTC, RonHaland approved these changes

2021-07-28 06:23 UTC, merged