Design and styling on LandingPage and RegisterGiver
capgemini-stavanger/gi-en-jul pull request #296
Opened 2021-07-27 12:29 UTC by elisabethnetland

Closes #task263
Added quicksand font as default
Added correct color-palette as default in index.js. 
Implemented basic styling on landingPage and registerUser, with the use of Material Ui's hook useStyles.
Changed navBar from  reactstrap and class component to MaterialUi using fuctional component.
Still left to change navBarAdmin. 
The styling is not responsive as it is now, and should be optimized for both desktop and mobile view.

2021-07-27 13:33 UTC, joffe97 requested changes
Good job! Added some nitpick comments.

2021-07-27 13:33 UTC, joffe97 commented on GiEnJul/ClientApp/src/common/components/NavBar.tsx
> +            <Drawer open={open} anchor="top" onClose={handleClose}>
Nitpick: The `open`probably here could be changed to `open={!!anchorEl}`. I think this would be cleaner, as the code on line 28 could be removed.

2021-07-27 13:33 UTC, joffe97 commented on GiEnJul/ClientApp/src/common/components/Styles.tsx
> +    borderRadius: "20px",
I think relative units should be used instead of static. Could `em` be used instead? This applies to other places as well.

2021-07-27 13:33 UTC, joffe97 commented on GiEnJul/ClientApp/src/styling/img/logo_gronn.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Could these filenames be changed into English ones?

2021-07-27 13:43 UTC, Sommerli submitted a review, later dismissed

2021-07-27 14:01 UTC, TheseusDeus requested changes
The ClientApp/package-lock.json file present is of version "1", while the one in master is of version "2", remove this one.

2021-07-28 10:55 UTC, joffe97 submitted a review, later dismissed

2021-07-28 11:06 UTC, TheseusDeus commented
> The ClientApp/package-lock.json file present is of version "1", while the one in master is of version "2", remove this one.

Incoming change for the PR will now delete the one in master. Either remove the file change from the PR or pull packagelock from master and merge into your branch

2021-07-29 07:10 UTC, TheseusDeus approved these changes

2021-07-29 07:10 UTC, merged