Institution info
capgemini-stavanger/gi-en-jul pull request #325
Opened 2021-08-02 13:32 UTC by TheseusDeus

Added more points to the institution info by request of Karianne

2021-08-02 13:59 UTC, Sommerli requested changes
En skrivefeil

2021-08-02 13:59 UTC, Sommerli commented on GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
> +  "Før du melder inn en familie må familien ha sag ja til å bli med, og du har all informasjon som trengs nedenfor.",
```suggestion
  "Før du melder inn en familie må familien ha sagt ja til å bli med, og du har all informasjon som trengs nedenfor.",
```

2021-08-03 06:15 UTC, joffe97 commented on GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
> +  "Gaveønskene skal ligge på rundt 300 per person. Kom gjerne med flere ønsker, så har giveren noe å velge mellom.",
Should this be `300 kr per person`?

2021-08-03 06:22 UTC, TheseusDeus commented on GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
> +  "Gaveønskene skal ligge på rundt 300 per person. Kom gjerne med flere ønsker, så har giveren noe å velge mellom.",
sure

2021-08-03 06:43 UTC, elisabethnetland approved these changes

2021-08-03 06:44 UTC, merged