Frontend - statistics
capgemini-stavanger/gi-en-jul pull request #344
Opened 2021-08-03 13:22 UTC by elisabethnetland

Closes #330

2021-08-03 13:36 UTC, joffe97 submitted a review, later dismissed

2021-08-03 13:36 UTC, joffe97 commented on GiEnJul/ClientApp/src/components/admin/overview/ConnectButton.tsx
> +  return <>{displayButton()}</>;
Could the wrapper (`<>...</>`) be removed here?

2021-08-03 13:36 UTC, joffe97 commented on GiEnJul/ClientApp/src/components/admin/overview/Statistics.tsx
> +  });
This should have been done with a useEffect hook, with giver as second parameter. Now the givers list is iterated upon every render. The suggestedMatch and confirmedMatch should also be put into a state.
For this to work, the states must be set after the loop has finished. The javascript filter method could probably be used here?

2021-08-03 15:50 UTC, Sommerli requested changes
Keep in mind that admins might have a smaller screen(laptop etc). The legend on left is somewhat hidden on smaller screens. This could be solved by simply moving the Statistics component up a tiny bit.
![image](https://user-images.githubusercontent.com/45152025/128045876-af7b10d9-9b61-4abd-ab9a-9c758862df70.png)

2021-08-03 15:50 UTC, Sommerli commented on GiEnJul/ClientApp/src/components/admin/overview/Statistics.tsx
> +  let suggestedMatch: number = 0;
Agree with Joachim, use filter to set these values
https://stackoverflow.com/a/47377879

2021-08-03 15:50 UTC, Sommerli commented on GiEnJul/ClientApp/src/components/admin/overview/Statistics.tsx
> +            {totalRecipints.toString()} familier
toString calls are not needed on the numbers in rest of file

2021-08-04 08:25 UTC, Sommerli approved these changes

2021-08-04 08:27 UTC, merged

2021-08-04 08:27 UTC, joffe97 approved these changes