Added POST /api/admin/event/ to create a new event
capgemini-stavanger/gi-en-jul pull request #408
Opened 2021-09-08 14:03 UTC by HGodal

Fixes #380 
Mentions #374 

Creating a POST route for /api/admin/event/ to create a new event, or update one that already exists.

2021-09-13 10:01 UTC, Sommerli requested changes
Nice work 👍 
Left a small suggestion for the controller method

Also i request clarification on the Event-class, as its keys has been swapped.

2021-09-15 06:27 UTC, HGodal commented on GiEnJul/Entities/Event.cs
> +        //PK - City
Yes 😅 I'll revert the change

2021-09-15 06:39 UTC, HGodal commented on GiEnJul/Controllers/AdminController.cs
> +            if (eventDto.StartDate <= System.DateTime.Today || eventDto.StartDate >= eventDto.EndDate)
startDate <= today throws an error if the start date is set to an earlier day than today. The criterion allows events to start at a later time.

2021-09-15 06:39 UTC, HGodal commented on GiEnJul/Controllers/AdminController.cs
> +            if (eventDto.StartDate <= System.DateTime.Today || eventDto.StartDate >= eventDto.EndDate)
> Dont know if there will be use cases where events are created with an upcoming startdate (startDate > DateTime.Today). We should ask what the admin thinks :)

startDate <= today throws an error if the start date is set to an earlier day than today. The criterion allows events to start at a later time.

2021-09-15 06:45 UTC, HGodal commented on GiEnJul/Entities/Event.cs
> +        public string EventType { get; set; }
I'll revert the name back to EventName to avoid confusion.

2021-09-15 07:46 UTC, TTorgersen approved these changes
Nice fixes:)

2021-09-15 08:00 UTC, Sommerli approved these changes

2021-09-15 08:02 UTC, merged