Dynamiccontactlist/398
capgemini-stavanger/gi-en-jul pull request #409
Opened 2021-09-09 11:28 UTC by SindreVatnaland

Static contact list on the landing page is updated to read and display data dynamically depending on active locations in the database.

Update requires additional columns in the database:
ContactPerson
Email
Facebook
Instagram

2021-09-13 10:21 UTC, Sommerli requested changes
Looks good, but there are some variable names that should be addressed. 
The name should reflect what a variable consist of and its usage

2021-09-13 10:21 UTC, Sommerli commented on ClientApp/src/components/landingPage/Macro.tsx
> +  const [xContact, setContactCards] = useState<ContactsData[]>([]);
xContact and setContactCards is inconsistent and hard to understand. 

https://reactjs.org/docs/hooks-state.html
states should always be named: [myState, setMyState] 

I suggest naming the state: contacts

2021-09-13 10:21 UTC, Sommerli commented on ClientApp/src/components/landingPage/Contact.tsx
> +export interface ContactsData {
The interface name should not be plural, as it represents a single contact.
Eg. ContactData or ContactInfo should ble more fitting.

2021-09-13 10:21 UTC, Sommerli commented on ClientApp/src/components/landingPage/Contact.tsx
> +console.log(contacts);
Unnecessary console.log

2021-09-13 10:21 UTC, Sommerli commented on ClientApp/src/components/landingPage/Contact.tsx
> +const listContacts = contacts.map((contact, index) =>
Could listContacts be renamed to Contacts or ContactList ?

This could also be put into the return, replacing {listContacts} at line 90.

2021-09-15 07:12 UTC, HGodal commented
Fill out the fields on the right side of the pull request, such as "Reviewers", "Asignees", "Project" and "Milestone". This will provide a better overview and make the pull request visible in the Projects tab.

2021-09-15 12:05 UTC, Sommerli approved these changes

2021-09-15 12:10 UTC, HGodal requested changes

2021-09-15 12:10 UTC, HGodal commented on GiEnJul/Dtos/GetContactsDto.cs
> +using System.Threading.Tasks;
Remember to remove unused imports.

2021-09-15 13:22 UTC, TTorgersen approved these changes

2021-09-15 13:23 UTC, Sommerli approved these changes

2021-09-15 13:59 UTC, SindreVatnaland commented on GiEnJul/Dtos/GetContactsDto.cs
> +using System.Threading.Tasks;
Imports removed

2021-09-15 14:02 UTC, TTorgersen approved these changes

2021-09-15 14:12 UTC, merged